---
# bla bla bla

- name: Installing repo for Java 8 in Ubuntu
  apt_repository: repo='ppa:openjdk-r/ppa'

- name: Ensure Java is installed.
  apt: 
    name: openjdk-8-jdk
    state: present

- name: Download Android SDK tools
  get_url: url={{ android_sdk_download_location }} dest=/tmp/sdk.zip

- name: Creates Android SDK directory
  file: path={{ android_sdk_install_location }} state=directory

- name: Extract Android SDK tools
  unarchive: src=/tmp/sdk.zip dest={{ android_sdk_install_location }} copy=no

- name: Set system wide PATH to contain Android SDK tools
  lineinfile: dest=/etc/environment regexp=^PATH line='PATH="/usr/local/sbin:/usr/local/bin:{{ android_sdk_install_location }}/tools:{{ android_sdk_install_location }}/tools/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games"'

- name: Set system wide ANDROID_HOME environment variable
  lineinfile: dest=/etc/environment regexp=^ANDROID_HOME line='ANDROID_HOME="{{ android_sdk_install_location }}"'

- name: Install emulator
  command: "echo y | {{ android_sdk_install_location }}/tools/bin/sdkmanager \"emulator\""
