---

- name: Copy image files to remote host
  synchronize:
    src: files/device-image
    dest: "{{ docker_tmp_images_path }}"

- name: Build an image
  docker_image:
    path: "{{ docker_tmp_images_path }}/device-image"
    name: "{{ docker_device_image_name }}"