---

- name: Installing repo for Java 8 in Ubuntu
  apt_repository:
    repo: 'ppa:openjdk-r/ppa'
    validate_certs: no

- name: Ensure Java is installed.
  apt:
    name: openjdk-8-jdk
    state: present
